# score.grafana.yaml
apiVersion: score.dev/v1b1
metadata:
  name: grafana-service
  annotations:
    app: grafana
service:
  # This defines the Kubernetes Service and can be used by an Ingress
  ports:
    http:
      port: 3000
      targetPort: 3000
containers:
  grafana:
    image: grafana/grafana
    variables:
      # The admin credentials are sourced from an 'environment' resource.
      # score-k8s will create a k8s Secret to provide these values.
      GF_SECURITY_ADMIN_USER: ${resources.env.GF_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${resources.env.GF_ADMIN_PASSWORD}
    # The 'files' directive tells score-k8s to create a ConfigMap
    # from the local grafana-datasource.yml file.
    files:
      /etc/grafana/provisioning/datasources/datasource.yml:
        source: ./grafana-datasource.yml
    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
    resources:
      requests:
        cpu: "250m"
        memory: "512Mi"
      limits:
        cpu: "500m"
        memory: "1Gi"
resources:
  # This resource declares the dependency on the Prometheus workload
  prometheus:
    type: service
    class: prometheus-service
  # This resource tells score-k8s to look for these values
  # and create a Secret from them.
  env:
    type: environment