# score.prometheus.yaml
apiVersion: score.dev/v1b1
metadata:
  name: prometheus-service
  annotations:
    # This translates the k8s label into a Score annotation
    app: prometheus
service:
  ports:
    # This defines the Kubernetes Service port
    http:
      port: 9090
      targetPort: 9090
containers:
  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    # The 'files' directive tells score-k8s to create a ConfigMap
    # from the local file and mount it into the container.
    files:
      /etc/prometheus/prometheus.yml:
        source: ./prometheus.yml
    readinessProbe:
      httpGet:
        path: /-/ready
        port: 9090
    # The 'volumes' directive tells score-k8s to create a PVC
    # and mount it into the container.
    volumes:
      /prometheus:
        source: ${resources.prom-data}
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"
      limits:
        cpu: "1"
        memory: "2Gi"
resources:
  # This resource declaration tells score-k8s to create the PersistentVolumeClaim
  prom-data:
    type: volume
    params:
      storage: 2Gi # Specifies the size for the PVC