name: ci
permissions:
  contents: read
  actions: write # Needed for workflow_dispatch
on:
  push:
jobs:
  detect-changed-dirs:
    runs-on: ubuntu-24.04
    outputs:
      dirs: ${{ steps.set-dirs.outputs.dirs }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2 # Needed to compare with previous commit
      - name: Debug changed files
        run: |
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD
          echo "Filtered files (score/*.yaml or Makefile):"
          git diff --name-only HEAD^ HEAD | grep '^examples/[^/]\+/\(\(score/.*\.yaml\)\|\(Makefile\)\)$' || echo "No relevant files found"
      - name: Find changed directories
        id: set-dirs
        run: |
          # Get changed score/*.yaml or Makefile in examples/*
          CHANGED_FILES=$(git diff --name-only HEAD^ HEAD | grep '^examples/[^/]\+/\(\(score/.*\.yaml\)\|\(Makefile\)\)$' || true)
          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed YAML files or Makefiles found, setting empty dirs"
            echo "dirs=[]" >> $GITHUB_OUTPUT
            exit 0
          fi
          # Extract unique directories
          DIRS_JSON=$(echo "$CHANGED_FILES" | sed 's|^examples/\([^/]\+\)/.*$|\1|' | sort -u | jq -R -s -c 'split("\n") | map(select(. != ""))')
          echo "dirs=$DIRS_JSON" >> $GITHUB_OUTPUT
          echo "Dirs output: $DIRS_JSON"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  trigger-directory-workflows:
    needs: detect-changed-dirs
    if: ${{ needs.detect-changed-dirs.outputs.dirs != '[]' }}
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dir: ${{ fromJson(needs.detect-changed-dirs.outputs.dirs) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check for workflow file
        run: |
          if [ ! -f examples/${{ matrix.dir }}/.github/workflows/ci.yaml ]; then
            echo "No ci.yaml found in examples/${{ matrix.dir }}/.github/workflows/"
            exit 1
          fi
      - name: Trigger directory workflow
        run: |
          gh workflow run ci.yaml \
            --repo ${{ github.repository }} \
            --ref ${{ github.ref }} \
            -f dir=${{ matrix.dir }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}