---
name: release
permissions:
  contents: read
  id-token: write
  packages: write
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory under examples/ to build (e.g., wordpress-mysql)'
        required: true
env:
  IMAGE_TAG: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.dir }}
jobs:
  detect-dockerfiles:
    runs-on: ubuntu-24.04
    outputs:
      dockerfiles: ${{ steps.set-dockerfiles.outputs.dockerfiles }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Debug directory contents
        run: |
          echo "Listing examples/${{ github.event.inputs.dir }}/apps"
          ls -la examples/${{ github.event.inputs.dir }}/apps || echo "Apps dir not found"
      - name: Find Dockerfiles in apps/
        id: set-dockerfiles
        run: |
          DIR=${{ github.event.inputs.dir }}
          DOCKERFILES=$(find examples/$DIR/apps -type f -name "Dockerfile" | \
            sed 's|examples/$DIR/apps/||' | sort -u || true)
          if [ -z "$DOCKERFILES" ]; then
            echo "No Dockerfiles found in examples/$DIR/apps/"
            exit 1
          fi
          DOCKERFILES_JSON=$(echo "$DOCKERFILES" | jq -R -s -c \
            'split("\n") | map(select(. != ""))')
          echo "dockerfiles=$DOCKERFILES_JSON" >> $GITHUB_OUTPUT
          echo "Dockerfiles: $DOCKERFILES_JSON"

  build-push:
    needs: detect-dockerfiles
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dockerfile: ${{ fromJson(needs.detect-dockerfiles.outputs.dockerfiles) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login \
            ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build and push container image
        uses: docker/build-push-action@v6
        with:
          context: examples/${{ github.event.inputs.dir }}/apps/${{ matrix.dockerfile }}
          file: examples/${{ github.event.inputs.dir }}/apps/${{ matrix.dockerfile }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/awesome-score-spec-examples/${{ matrix.dockerfile }}:${{ env.IMAGE_TAG }}
            ghcr.io/${{ github.repository_owner }}/awesome-score-spec-examples/${{ matrix.dockerfile }}:latest