name: release
permissions:
  contents: read
  id-token: write
  packages: write
on:
  push:
    tags:        
      - 'v*'
env:
  IMAGE_TAG: ${{ github.ref_name }}
  IMAGE_NAME: angular-web
jobs:
  build-push:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: login to ghcr
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login \
              ghcr.io \
              -u $ \
              --password-stdin
      - name: build and push {{ env.IMAGE_NAME }} container image
        uses: docker/build-push-action@v6
        with:
          context: app
          platforms: linux/amd64,linux/arm64
          file: app/Dockerfile
          push: true
          tags: "ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }},ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest"